# 4. Installtion of git ,maven, docker using a playbook:

- name: Install git, maven,docker
  hosts: all
  become: yes
  tasks:
    - name: Install git
      yum: 
        name: git
        state: present
    - name: Install Maven
      yum: 
        name: maven
        state: present
    - name: Install docker
      yum: 
        name: docker
        state: presnet
    - name: Print installed message
      debug: 
        msg: "Docker has been installed successfully!"
    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

# 6. Deploy a nginx web page using a playbook:

- name: install and deploy nginx webpage
  hosts: all
  becomes: yes
  tasks:
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: enable nginix
      service: 
        name: nginx
        state: started
        enabled: yes
    - name: deploy nginx
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
    - name: Print deployed message
      debug: 
        msg: "Nginx webpage has been deployed successfully!"
    - name: restart nginx
      service:
        name: nginx
        state: restarted
